
CREATE TABLE category(
  id INT AUTO_INCREMENT PRIMARY KEY ,
  name VARCHAR(64) NOT NULL COMMENT '分类名称'
) DEFAULT CHAR SET utf8  ENGINE=InnoDB ;

CREATE TABLE post(
  id INT AUTO_INCREMENT PRIMARY KEY ,
  titile VARCHAR(64) NOT NULL COMMENT '标题',
  content TEXT COMMENT '正文',
  created_at TIMESTAMP NOT NULL DEFAULT current_timestamp,
  updated_at TIMESTAMP
)DEFAULT CHAR SET utf8  ENGINE=InnoDB;

ALTER TABLE post CHANGE COLUMN titile title VARCHAR(64) NOT NULL COMMENT '标题';